Repository FITIFITBANnerit/backend, pull requests merged in 2025-04, with the labels that each got.

#11 feat: 현수막 신고 및 현수막 정보 저장
  src/main/java/com/BANnerIt/server/api/banner/controller/BannerController.java
  src/main/java/com/BANnerIt/server/api/banner/controller/ReportController.java
  src/main/java/com/BANnerIt/server/api/banner/domain/Banner.java
  src/main/java/com/BANnerIt/server/api/banner/domain/BannerStatus.java
  src/main/java/com/BANnerIt/server/api/banner/domain/Report.java
  src/main/java/com/BANnerIt/server/api/banner/domain/ReportStatus.java
  src/main/java/com/BANnerIt/server/api/banner/dto/ErrorResponse.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/BannerDetailsDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/BannerDetailsWithIdDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/BannerInfoDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/SaveBannerRequest.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/UpdateBannerRequest.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/AddressDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/LocationDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/ReportDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/ReportLogDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/ReportLogsResponse.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/SaveReportRequest.java
  src/main/java/com/BANnerIt/server/api/banner/repository/BannerRepository.java
  src/main/java/com/BANnerIt/server/api/banner/repository/ReportRepository.java
  src/main/java/com/BANnerIt/server/api/banner/service/BannerService.java
  src/main/java/com/BANnerIt/server/api/banner/service/ReportService.java
  src/main/java/com/BANnerIt/server/api/user/Member.java
Labels: 🚀feat, ♻️refactor

#19 feat: S3와 spring boot 연동
  build.gradle
  src/main/java/com/BANnerIt/server/api/s3/controller/S3Controller.java
  src/main/java/com/BANnerIt/server/api/s3/domain/Image.java
  src/main/java/com/BANnerIt/server/api/s3/dto/PresignedUrlDto.java
  src/main/java/com/BANnerIt/server/api/s3/dto/PresignedUrlRequest.java
  src/main/java/com/BANnerIt/server/api/s3/dto/PresignedUrlResponse.java
  src/main/java/com/BANnerIt/server/api/s3/repository/ImageRepository.java
  src/main/java/com/BANnerIt/server/api/s3/service/S3Service.java
  src/main/java/com/BANnerIt/server/global/config/S3Config.java
Labels: 🚀feat

#24 Feat/login
  src/main/java/com/BANnerIt/server/api/Auth/controller/OAuthController.java
  src/main/java/com/BANnerIt/server/api/Auth/service/OAuthService.java
  src/main/java/com/BANnerIt/server/api/user/controller/MemberController.java
  src/main/java/com/BANnerIt/server/api/user/dto/MemberResponse.java
  src/main/java/com/BANnerIt/server/api/user/dto/UserData.java
  src/main/java/com/BANnerIt/server/global/exception/ApiResponse.java
  src/main/java/com/BANnerIt/server/global/exception/ExceptionDto.java
  src/main/java/com/BANnerIt/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/BANnerIt/server/userTest/MemberControllerTest.java
  src/test/java/com/BANnerIt/server/userTest/OAuthControllerTest.java
Labels: 🏷️merge

#32 Feat/login
  src/main/java/com/BANnerIt/server/global/config/CorsConfig.java
  src/main/java/com/BANnerIt/server/global/config/SecurityConfig.java
Labels: 🏷️merge

#34 Feat/banner: 신고 사진 저장 및 조회
  src/main/java/com/BANnerIt/server/api/banner/controller/BannerController.java
  src/main/java/com/BANnerIt/server/api/banner/controller/ReportController.java
  src/main/java/com/BANnerIt/server/api/banner/domain/Report.java
  src/main/java/com/BANnerIt/server/api/banner/domain/ReportStatus.java
  src/main/java/com/BANnerIt/server/api/banner/dto/ErrorResponse.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/BannerDetailsDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/BannerDetailsWithIdDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/BannerInfoDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/SaveBannerRequest.java
  src/main/java/com/BANnerIt/server/api/banner/dto/banner/UpdateBannerRequest.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/ReportDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/ReportLogDto.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/ReportLogsResponse.java
  src/main/java/com/BANnerIt/server/api/banner/dto/report/SaveReportRequest.java
  src/main/java/com/BANnerIt/server/api/banner/service/BannerService.java
  src/main/java/com/BANnerIt/server/api/banner/service/ReportService.java
  src/main/java/com/BANnerIt/server/api/s3/controller/S3Controller.java
  src/main/java/com/BANnerIt/server/api/s3/domain/Image.java
  src/main/java/com/BANnerIt/server/api/s3/dto/PresignedUrlDto.java
  src/main/java/com/BANnerIt/server/api/s3/dto/PresignedUrlResponse.java
  src/main/java/com/BANnerIt/server/api/s3/service/S3Service.java
  src/main/java/com/BANnerIt/server/global/exception/ApiResponseUtil.java
Labels: 🚀feat, 🏷️merge

#49 fix: 비동기 배너 저장 시 트랜잭션 누락 문제 해결 (REQUIRES_NEW 적용)
  src/main/java/com/BANnerIt/server/api/banner/service/BannerService.java
Labels: 🏷️merge, 🐛fix
